//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public decimal Giatien { get; set; }
        public string NhanHieu { get; set; }
        public string Image { get; set; }
    }
}
